### PR TITLE
tentative to perform docker build with Gurobi 9.0.2

### PR DESCRIPTION
**Pull request by davethejoy**
Tentative to rebuild chordatlas with Gurobi 9.0.2

### CODE REVIEW

**Comment by davethejoy** [comment]
Still getting the following error:
```
[ERROR] Failed to execute goal on project chordatlas: Could not resolve dependencies for project org.twak.chordatlas:chordatlas:jar:0.0.1: Could not find artifact gurobi:gurobi-linux64:jar:9.0.2 in jitpack.io (https://jitpack.io) -> [Help 1]
```

**Comment by twak** [comment]
thanks, I've copied all the bits I need. I won't actually do the merge because things have gotten complicated in git.

**Comment by davethejoy** [comment]
Thanks let me know what to pull do I can test it

**Comment by twak** [comment]
instructions [here](https://github.com/twak/chordatlas/wiki/build-instructions) to build with docker and Gurobi 9.

**Pull request closed without merging**
